# Generated by Django 5.2.3 on 2025-06-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_disponibilidad', models.DateTimeField()),
                ('fecha_ultimo_mensaje', models.DateTimeField()),
                ('intentos_de_contacto', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('estado_finca', models.BooleanField(default=True)),
                ('estado_Ciencuadras', models.BooleanField(default=True)),
            ],
        ),
    ]
