# Generated by Django 5.2.3 on 2025-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='gestion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_disponibilidad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_ultimo_mensaje',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
